"""Seed the glossary search database.

Indexes the maven_training corpus. Falls back to sample military/data terms
if the corpus directory is not available.

Run:  python -m apps.glossary_search.seed
"""

from __future__ import annotations

from pathlib import Path

from . import db
from .db import Term, get_session, init_db

CORPUS_ROOT = Path(__file__).resolve().parent.parent.parent / "maven_training"

# ---------------------------------------------------------------------------
# Fallback sample terms — used when the corpus directory is not available
# ---------------------------------------------------------------------------

_SAMPLE_TERMS: list[dict] = [
    {"term": "OPDATA", "definition": "Operational Data — data generated by, or directly supporting, operational activities within an Area of Responsibility (AOR). Includes readiness, logistics, personnel, and intelligence feeds.", "category": "ACRONYM"},
    {"term": "AOR", "definition": "Area of Responsibility — the geographic region assigned to a combatant command or subordinate unit for operational oversight.", "category": "ACRONYM"},
    {"term": "WFF", "definition": "Warfighting Function — one of six mutually supporting military activities integrated in operations: Intelligence, Fires, Movement & Maneuver, Sustainment, Protection, Mission Command.", "category": "ACRONYM"},
    {"term": "SITREP", "definition": "Situation Report — a periodic report providing the current status of operations, including friendly and enemy situation, logistics, and significant activities.", "category": "ACRONYM"},
    {"term": "ETL", "definition": "Extract, Transform, Load — a data integration pattern that extracts data from source systems, transforms it into a standardized format, and loads it into a target dataset or data warehouse.", "category": "CONCEPT"},
    {"term": "OSDK", "definition": "Ontology Software Development Kit — Palantir's SDK for building external applications that interact with the Foundry Ontology, including object queries, action execution, and real-time subscriptions.", "category": "ACRONYM"},
    {"term": "Ontology", "definition": "A structured representation of data as objects with typed properties and relationships (links). In Foundry, the Ontology is the semantic layer that maps raw datasets into domain-meaningful entities like Soldiers, Units, Equipment, and their interconnections.", "category": "GLOSSARY"},
    {"term": "AIP", "definition": "Artificial Intelligence Platform — Palantir's generative AI layer in Foundry that enables natural language interaction with data, AI-assisted analysis, and autonomous agent workflows grounded in Ontology context.", "category": "ACRONYM"},
    {"term": "Pipeline", "definition": "A sequence of data transformation steps that processes raw data into a curated, analysis-ready form. Pipelines read from upstream datasets, apply cleaning/enrichment/aggregation logic, and write to downstream datasets.", "category": "GLOSSARY"},
    {"term": "Object Type", "definition": "A class definition in the Foundry Ontology representing a real-world entity (e.g., Soldier, Vehicle, Unit). Backed by a curated dataset, with properties mapped to dataset columns and links defining relationships to other Object Types.", "category": "GLOSSARY"},
    {"term": "C2", "definition": "Command and Control — the exercise of authority and direction by a properly designated commander over assigned and attached forces in the accomplishment of the mission.", "category": "ACRONYM"},
    {"term": "MDMP", "definition": "Military Decision-Making Process — the Army's planning methodology used by battalion and above to produce orders. Consists of seven steps from receipt of mission through orders production.", "category": "ACRONYM"},
    {"term": "DTG", "definition": "Date-Time Group — the standard military format for expressing date and time: DDHHMMZMmmYYYY (e.g., 151430ZMAR2026). Used in all military communications and reporting.", "category": "ACRONYM"},
    {"term": "MSS", "definition": "Maven Smart System — the Army's operational data platform built on Palantir Foundry. Provides data integration, analytics, ontology modeling, and application development for operational decision-making.", "category": "ACRONYM"},
    {"term": "CDA", "definition": "Cross-Domain Architecture — the overarching data architecture framework for USAREUR-AF that defines how operational data flows across warfighting functions, classification levels, and coalition boundaries.", "category": "ACRONYM"},
    {"term": "Transform", "definition": "A data processing step in a Foundry pipeline that reads one or more input datasets, applies business logic (filtering, joining, aggregating, enriching), and writes the result to an output dataset. Transforms are the building blocks of data pipelines.", "category": "GLOSSARY"},
    {"term": "Aggregation", "definition": "A data transformation operation that groups records by one or more fields and computes summary statistics (count, sum, average, min, max) for each group. Collapses many rows into fewer summarized rows.", "category": "GLOSSARY"},
    {"term": "Dashboard", "definition": "A visual display summarizing key data points, metrics, and status indicators on a single screen for quick situational awareness. In Foundry, dashboards are built in Workshop (Ontology data) or Quiver/Contour (dataset data).", "category": "GLOSSARY"},
    {"term": "EXORD", "definition": "Execution Order — a directive issued to initiate or modify operations. In the MSS context, used to authorize deployment of data products or pipeline changes to production.", "category": "ACRONYM"},
    {"term": "RAG Status", "definition": "Red-Amber-Green status indicator used to communicate readiness or health at a glance. Red indicates critical/non-mission-capable, Amber indicates degraded/partially capable, Green indicates fully mission capable.", "category": "CONCEPT"},
    {"term": "Data Steward", "definition": "An individual responsible for the quality, integrity, and governance of a specific dataset or data domain. Ensures data meets standards, is properly documented, and access controls are enforced.", "category": "CONCEPT"},
    {"term": "Schema", "definition": "The structural definition of a dataset — the column names, data types, constraints, and relationships that define what the data contains. Schema changes must be managed carefully to avoid breaking downstream consumers.", "category": "GLOSSARY"},
    {"term": "Idempotency", "definition": "The property of an operation where executing it multiple times produces the same result as executing it once. Critical for data pipelines: an idempotent pipeline can be safely rerun without creating duplicates or corrupting data.", "category": "CONCEPT"},
    {"term": "Link Type", "definition": "A typed relationship between two Object Types in the Foundry Ontology. Defined with cardinality (one-to-one, one-to-many, many-to-many) and backed by foreign key columns in the underlying datasets.", "category": "GLOSSARY"},
    {"term": "Action Type", "definition": "A defined mutation operation in the Foundry Ontology that modifies object properties or creates/deletes objects. Actions enforce business rules via validation logic and provide an auditable record of data changes.", "category": "GLOSSARY"},
    {"term": "Workshop", "definition": "Foundry's application builder module for creating operational applications backed by the Ontology. Workshop apps display objects, execute actions, and provide interactive dashboards without custom code.", "category": "GLOSSARY"},
    {"term": "Contour", "definition": "Foundry's interactive data exploration tool that enables analysts to query, filter, pivot, and visualize datasets without writing code. Supports branching analysis workflows.", "category": "GLOSSARY"},
    {"term": "DODID", "definition": "Department of Defense Identification Number — a unique 10-digit number assigned to every service member, used as a primary identifier across personnel and readiness systems.", "category": "ACRONYM"},
    {"term": "TEO", "definition": "Training and Evaluation Outline — a document specifying the tasks, conditions, standards, and evaluation criteria for a training event.", "category": "ACRONYM"},
    {"term": "MTP", "definition": "Master Training Plan — the overarching plan governing a unit's training activities, objectives, and resource allocation over a specified period.", "category": "ACRONYM"},
    {"term": "POI", "definition": "Program of Instruction — the detailed curriculum document specifying learning objectives, lesson sequence, hours, and assessment criteria for a course.", "category": "ACRONYM"},
    {"term": "CAD", "definition": "Course Administrative Data — the administrative metadata for a training course including course number, duration, prerequisites, class size, and resource requirements.", "category": "ACRONYM"},
    {"term": "C2DAO", "definition": "Command and Control Data Analytics Office — the organizational element responsible for data operations, analytics, and MSS platform management within USAREUR-AF.", "category": "ACRONYM"},
    {"term": "Parquet", "definition": "A columnar file format optimized for analytical workloads. Stores data by column rather than by row, enabling efficient compression and fast queries on subsets of columns. Foundry stores dataset data internally in Parquet format.", "category": "CONCEPT"},
    {"term": "Data Lineage", "definition": "The documented chain of transformations and provenance from a data record's original source through every processing step to its final curated form. Lineage enables auditability, debugging, and trust in data products.", "category": "CONCEPT"},
    {"term": "ORSA", "definition": "Operations Research / Systems Analysis — the application of quantitative analytical methods to support military decision-making, including modeling, simulation, statistical analysis, and optimization.", "category": "ACRONYM"},
    {"term": "MTT", "definition": "Mobile Training Team — a deployable instructor cadre that delivers training at the requesting unit's location rather than requiring travel to a schoolhouse.", "category": "ACRONYM"},
    {"term": "LSCO", "definition": "Large-Scale Combat Operations — the conduct of military operations against a near-peer adversary with significant combat power, requiring the integration of all warfighting functions at scale.", "category": "ACRONYM"},
    {"term": "BLUF", "definition": "Bottom Line Up Front — a communication technique placing the most important information at the beginning of a message or briefing, followed by supporting details.", "category": "ACRONYM"},
    {"term": "ADR", "definition": "Architecture Decision Record — a document capturing a significant architectural decision, the context and constraints that drove it, the alternatives considered, and the rationale for the chosen approach.", "category": "ACRONYM"},
    {"term": "Deduplication", "definition": "The process of identifying and removing duplicate records from a dataset. Essential for maintaining data quality, especially in append-mode pipelines where retries or overlapping ingestion windows can introduce duplicates.", "category": "CONCEPT"},
    {"term": "Foreign Key", "definition": "A column in one dataset that references the primary key of another dataset, establishing a relationship between the two. In the Ontology, foreign keys back Link Types between Object Types.", "category": "CONCEPT"},
    {"term": "Incremental Processing", "definition": "A pipeline pattern that processes only new or changed records since the last run, rather than reprocessing the entire dataset. Reduces compute time and cost for large, frequently-updated datasets.", "category": "CONCEPT"},
    {"term": "SOP", "definition": "Standard Operating Procedure — a documented set of step-by-step instructions for performing a routine operation. SOPs ensure consistency, reduce errors, and encode institutional knowledge.", "category": "ACRONYM"},
    {"term": "TASKORD", "definition": "Tasking Order — a directive that assigns specific tasks to subordinate units, including the task, purpose, and any coordinating instructions.", "category": "ACRONYM"},
    {"term": "FBC", "definition": "Foundry Bootcamp — a quarterly 5-day intensive training event where participants build MSS solutions for real operational problems. Prerequisite: SL 2 Go. Does NOT grant SL 3 credit.", "category": "ACRONYM"},
    {"term": "Snapshot Transaction", "definition": "A dataset write operation that replaces all existing data with the new output on each run. Contrasted with Append Transaction, which adds new rows without deleting previous data. Snapshot transactions are inherently idempotent.", "category": "GLOSSARY"},
    {"term": "Watermark", "definition": "A checkpoint marker (typically a timestamp or sequence number) indicating the last record successfully processed by an incremental pipeline. Used to determine where the next run should resume.", "category": "CONCEPT"},
    {"term": "Property", "definition": "An attribute of an Object Type in the Foundry Ontology, mapped to a column in the backing dataset. Properties have typed values (string, integer, timestamp, etc.) and can be searched, filtered, and displayed in applications.", "category": "GLOSSARY"},
]


def _seed_fallback() -> int:
    """Insert sample terms when the corpus directory is unavailable."""
    init_db()
    session = get_session()
    # Clear existing
    session.query(Term).delete()
    session.commit()

    for entry in _SAMPLE_TERMS:
        term = Term(
            term=entry["term"],
            definition=entry["definition"],
            source_file="seed.py (sample data)",
            source_line=0,
            category=entry["category"],
        )
        session.add(term)

    session.commit()
    count = session.query(Term).count()
    session.close()
    return count


def main() -> None:
    """Run the seeder: index from corpus or fall back to sample data."""
    try:
        if CORPUS_ROOT.is_dir():
            print(f"Indexing from corpus: {CORPUS_ROOT}")
            count = db.reindex(CORPUS_ROOT)
            print(f"Indexed {count} terms from markdown files.")
        else:
            raise FileNotFoundError(f"Corpus root not found: {CORPUS_ROOT}")
    except Exception as exc:
        print(f"Corpus indexing failed ({exc}); loading fallback sample terms...")
        count = _seed_fallback()
        print(f"Loaded {count} sample terms.")

    # Print summary
    stats = db.get_stats()
    print(f"\nIndex summary:")
    print(f"  Total terms:  {stats['total_terms']}")
    print(f"  Source files:  {stats['source_files']}")
    for cat in stats["by_category"]:
        print(f"  {cat['category']:12s}  {cat['count']}")


if __name__ == "__main__":
    main()
